spring.application.name=ploy_tech_course

spring.datasource.url=jdbc:mariadb://218.53.99.61:3306/ploytechcourse
spring.datasource.username=plteco
spring.datasource.password=ploytechcourse
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

server.address=0.0.0.0
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ploytechcourse@gmail.com
spring.mail.password=voecbmhsrqxwnuad
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.starttls.enable=true

spring.cloud.gcp.storage.project-id=graphite-ally-448608-t2
spring.cloud.gcp.storage.credentials.location=classpath:graphite-ally-448608-t2-42698c9bcc52.json
spring.cloud.gcp.storage.bucket=ploytechcourse


spring.jwt.secret=flkasdjflasjdflajsdlfjadsjflajkldffjfjdlqwyegqwuyetiuqwyiahdxbschdsvuhghfweyrgewghkhkfcjndesbjchdeguwyqhabhkjcbf

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.example=TRACE