spring.application.name=ploy_tech_course

spring.datasource.url=jdbc:mariadb://svc.sel4.cloudtype.app:30350/ploytechcourse
spring.datasource.username=root
spring.datasource.password=PloyTechCourse2025
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
