spring.application.name=ploy_tech_course

spring.datasource.url=jdbc:mariadb://34.22.107.183:3306/ploytechcourse
spring.datasource.username=plteco
spring.datasource.password=ploytechcourse
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

server.address=0.0.0.0
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ploytechcourse@gmail.com
spring.mail.password=voecbmhsrqxwnuad
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.starttls.enable=true


spring.jwt.secret=flkasdjflasjdflajsdlfjadsjflajkldffjfjdlqwyegqwuyetiuqwyiahdxbschdsvuhghfweyrgewghkhkfcjndesbjchdeguwyqhabhkjcbf

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.example=TRACE